### PR TITLE
Fixed invalid switch statement lua when default was not the last case

### LINKED ISSUE #967: default should be last case in switch statement
errored:
[default as first case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtykCmAZhgK4A2EAFyMAkCIAOAJzA4ICAEQdu-CPIKiRAI0nsM5ZqyhZ2cAIzCxUmXPkA5APK2Aomo3bd+kUeAmATBYlpWQVUABkAQQBlSNcxdz1RbxMAZgCrYPknAA0ABVD7SIBJADUXdVYKuHj9AF8gA)
[default as addition to first case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtykCmAZhgK4A2EAFzNWULOzgBGYQEgZABwBOYHBAQAiAHIB5TQFF1BRnIBGi9hnLGxwCQCZZC5ao2oAMgEEAyl8PGZZhZWMjYSAMyOSipq6noAGgAKbtpeAJIAagZGrDlwgZaMAL5AA)
[default as middle case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg0hwBmGAK4AbCPyFiJU6QePmIq9Vp16B7YFwBMVkeKSMqgAMgCCAMoRLkJuuoJeXADM-jZB0koAGgAKIfIRAJIAaipqrOVwcXoAvkA)
[default as addition to middle case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg0hwBmGAK4AbCPwHtgXAExWR4yTNQAZAIIBlL6vVadPWtOOABmRzEJKWklAA0ABTd5LwBJADUVNVZsuADdRgBfIA)
[default with addition](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg9sC4AmfkLESp01ABkAggGV7q9Vp16BBrgGZTI8ZJklAA0ABWt5ewBJADUVNVYEuFddQVIOADMMAFcAGwhTTzgAFl9zAOk0zNyIZyFkvQBfIA)
working:
[default as last case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg9sC4AmfkLESp01ABkAggGV7q9Vp16BBrgGZTI8ZJklAA0ABWt5ewBJADUVNVYEuFddQVIOADMMAFcAGwhfcwDpNMzciGchZL0AXyA)
[`case 5:\ndefault:`](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg9sC4AmfkLESp01ABkAggGV7q9Vp16BBrgGZTI8ZJklAA0ABWt5ewBJADUVNVYEuFddfU44ABZTUg4AMwwAVwAbCF9zAOlsvKKIZyFkvQBfIA)

### PR DESCRIPTION
**Pull request by Perryvw**
Fixes #967

### CODE REVIEW

File: src/transformation/visitors/switch.ts [hunk 1]
```diff
@@ -18,10 +18,13 @@ export const transformSwitchStatement: FunctionVisitor<ts.SwitchStatement> = (st
 
     let statements: lua.Statement[] = [];
 
-    const caseClauses = statement.caseBlock.clauses.filter(ts.isCaseClause);
-
     // Starting from the back, concatenating ifs into one big if/elseif statement
-    const concatenatedIf = caseClauses.reduceRight((previousCondition, clause, index) => {
+    const concatenatedIf = statement.caseBlock.clauses.reduceRight((previousCondition, clause, index) => {
```
Comment (lolleko) [inline src/transformation/visitors/switch.ts:22]: Not, related to this PR. But I find this reduceRight call extremely hard to read. If you want to you can refactor it. maybe by splitting the generation of the statements and the concatenation of the statements?
```ts
const ifStatementsForCases = statement.caseBlock.clauses.filter(!ts.isDefaultClause(clause)).map(
    ...
    return lua.createIfStatement(condition, lua.createBlock([goto])));
);
const concatenatedIf = ifStatementsForCases.reduceRight((prev, ifStatement) => {
    prev.elseBlock = ifStatement;
    return ifStatement;
});
```

If not, I am fine with merging the PR as it is.

**Review by lolleko — APPROVED** [review]
