### PR TITLE
Fix side effects in string index causing issues

### LINKED ISSUE #867: Indexing on string fails when index is an expression with side effects
Indexing on strings (e.g., `myString[7]`) duplicates the passed index expression, which results in incorrect code when the index expression has side effects, such as incrementing a value (`myString[i++]`).

Example, which would produce the string `"01"` instead of the expected `"0"`:
https://typescripttolua.github.io/play/#code/FAGwpgLgBAllC8UAMBuUkoGcICcFQCIkBGAJgLWGxwG0YBqegXTSA

### PR DESCRIPTION
**Pull request by Perryvw**
Fixes #867

### CODE REVIEW

File: src/transformation/visitors/access.ts [hunk 1]
```diff
@@ -31,19 +31,13 @@ export const transformElementAccessExpression: FunctionVisitor<ts.ElementAccessE
...
-        return lua.createCallExpression(
-            lua.createTableIndexExpression(lua.createIdentifier("string"), lua.createStringLiteral("sub")),
-            [table, createExpressionPlusOne(index), createExpressionPlusOne(index)],
-            expression
-        );
+        return transformStringIndex(context, expression);
     }
 
+    const table = context.transformExpression(expression.expression);
     return lua.createTableIndexExpression(table, transformElementAccessArgument(context, expression), expression);
```
Comment (ark120202) [inline src/transformation/visitors/access.ts:41]: That `table` variable name might be a bit confusing, since you don't necessarily access a property on a table. And in general the variable in this case doesn't seem to be very helpful here
```suggestion
    return lua.createTableIndexExpression(
        context.transformExpression(expression.expression),
        transformElementAccessArgument(context, expression),
        expression
     );
```
