### PR TITLE
Fixed incorrect escaping of fields

### LINKED ISSUE #833: table properties using builtin names are incorrectly marked as unsafe and renamed with underscores
Using identifiers in the builtins list as property names is valid Lua:
```lua
local Vector = {}
Vector.__index = Vector
function Vector.new(x,y)
    return setmetatable({
        x = x,
        y = y
    }, Vector)
end

function Vector:unpack()
    return self.x, self.y
end

local v = Vector.new(2,3)
local x,y = v:unpack()
print(x,y)
```
If I were to write a declaration for this:
```typescript
interface Vector {
    new: (this: void, x: number, y: number) => Vector;
    /** @tupleReturn **/
    unpack(): [number, number];
}
let vec2 = {} as Vector;

let v = vec2.new(2,3);
let [x,y] = v.unpack();
let [a,b] = v["unpack"]();
```
which compiles to:
```lua
vec2 = {}
v = vec2.new(2, 3)
x, y = v:____unpack()
a, b = v.unpack(v)
```

___unpack() will cause an error. Accessing it via string index is currently a workaround.

I believe this is related to #789

### PR DESCRIPTION
**Pull request by Perryvw**
Fixes #833, #789, #846

### CODE REVIEW

File: src/transformation/visitors/call.ts [hunk 1]
```diff
@@ -117,7 +116,7 @@ export function transformContextualCallExpression(
 
         return lua.createMethodCallExpression(
             table,
-            transformIdentifier(context, left.name),
+            lua.createIdentifier(left.name.text, left.name),
```
Comment (ark120202) [inline src/transformation/visitors/call.ts]: Would that work for syntactically invalid identifiers?

File: src/transformation/visitors/class/members/constructor.ts [hunk 2]
```diff
@@ -66,13 +66,15 @@ export function transformConstructorDeclaration(
...
-        const assignment = lua.createAssignmentStatement(
-            lua.createTableIndexExpression(createSelfIdentifier(), lua.createStringLiteral(declarationName.text)),
-            declarationName
-        );
-        bodyWithFieldInitializers.push(assignment);
+        if (ts.isIdentifier(declaration.name)) {
+            // self.declarationName = declarationName
+            const assignment = lua.createAssignmentStatement(
+                lua.createTableIndexExpression(createSelfIdentifier(), lua.createStringLiteral(declaration.name.text)),
+                transformIdentifier(context, declaration.name as ts.Identifier)
```
Comment (ark120202) [inline src/transformation/visitors/class/members/constructor.ts]:
```suggestion
                transformIdentifier(context, declaration.name)
```
