### PR TITLE
Constrained generic fixes

### LINKED ISSUE #489: Array detection fails on constrained generics
## Input
```typescript
function f<A extends any[]>(a: A){
  a.forEach(v => console.log(v));
}
```
## Current Result
```lua
f = function(self, a)
    a:forEach(function(____, v)
        return print(v);
    end);
end;
```
## Expected Result
```lua
f = function(self, a)
    __TS__ArrayForEach((a), function(____, v)
        return print(v);
    end);
end;
```

### PR DESCRIPTION
**Pull request by hazzard993**
Closes #489

Also fixed it for strings too. Thanks @ark120202 for the solution idea

### CODE REVIEW

File: src/TSHelper.ts [hunk 1]
```diff
@@ -157,9 +164,16 @@ export function isExplicitArrayType(type: ts.Type, checker: ts.TypeChecker, prog
...
+        const baseConstraint = checker.getBaseConstraintOfType(type);
+        if (baseConstraint) {
+            return isExplicitArrayType(baseConstraint, checker, program);
+        }
+    }
+
     const flags = ts.NodeBuilderFlags.InTypeAlias | ts.NodeBuilderFlags.AllowEmptyTuple;
     const typeNode = checker.typeToTypeNode(type, undefined, flags);
-    return typeNode !== undefined && (ts.isArrayTypeNode(typeNode) || ts.isTupleTypeNode(typeNode));
+    return typeNode !== undefined ? ts.isArrayTypeNode(typeNode) || ts.isTupleTypeNode(typeNode) : false;
```
Comment (Perryvw) [inline src/TSHelper.ts]: I prefer the previous version of this line, why the change?

Comment (hazzard993) [reply src/TSHelper.ts]: Shouldn't have touched that line, going with preference

File: src/TSHelper.ts [hunk 2]
```diff
@@ -157,6 +164,13 @@ export function isExplicitArrayType(type: ts.Type, checker: ts.TypeChecker, prog
         return true;
     }
 
+    if (type.symbol) {
```
Comment (ark120202) [inline src/TSHelper.ts]: It shouldn't affect correctness, but would it maybe be better to make it a first check in the function, so that a technical detail is checked before the actual function logic?

File: test/unit/array.spec.ts [hunk 3]
```diff
@@ -226,3 +226,36 @@ test.each([`["foo", "bar"].length`, `["foo", "bar"][0]`, `[() => "foo", () => "b
         expect(util.transpileAndExecute(code)).toBe(expectResult);
     }
 );
+
+const genericChecks = [
+    "function generic<T extends number[]>(array: T)",
+    "function generic<T extends [...number[]]>(array: T)",
+    "function generic<T extends any>(array: T[])",
+    "type ArrayType = number[]; function generic<T extends ArrayType>(array: T)",
+];
```
Comment (ark120202) [inline test/unit/array.spec.ts]: Few cases that may worth to be tested:

```suggestion
    "function generic<T extends number[]>(array: T & {})",
    "function generic<T extends number[] & {}>(array: T)",
];
```
