### PR TITLE
Handling return from try and catch

### LINKED ISSUE #252: Returning inside try block fails
```ts
function foo() {
    try {
        return "foo";
    } finally {
        return "bar";
    }
}
print(foo());
```
```lua
function foo()
    xpcall(function()
        return "foo"
end,
function(e)
end)
    return "bar"
end
print(foo()); --Prints "bar"
```
The return statement only returns out of the function passed to xpcall. I'm not totally sure what a good way to deal with this would be.

### PR DESCRIPTION
**Pull request by tomblind**
fixes #252 

To support proper returning from `try`/`catch` (while still executing `finally`), a `true` literal is prepended to returned values. This is checked after `finally` is executed and the return value is forwarded on. Note that the `catch` block will always be wrapped in an IIFE in this case.
```ts
function foobar() {
    try {
        return mayThrow();
    } catch (err) {
        return "error thrown: " + err;
    } finally {
        console.log("finally");
    }
}
```
=>
```lua
function foobar(self)
    do
        local ____TS_try, err, ____TS_returnValue = pcall(function()
            return true, mayThrow()
        end)
        if not ____TS_try then
            err, ____TS_returnValue = (function()
                return true, "error thrown: " .. tostring(err)
            end)()
        end
        do
            print("finally")
        end
        if err then
            return ____TS_returnValue
        end
    end
end
```

In the case of `@tupleReturn` functions, the return value will be wrapped and later unpacked when forwarded.
```ts
/** @tupleReturn */
function foobar() {
    try {
        return [mayThrow(), mayThrow()];
    } catch (err) {
        return ["error thrown", err];
    } finally {
        console.log("finally");
    }
}
```
=>
```lua
function foobar(self)
    do
        local ____TS_try, err, ____TS_returnValue = pcall(function()
            return true, ({
                mayThrow(),
                mayThrow(),
            })
        end)
        if not ____TS_try then
            err, ____TS_returnValue = (function()
                return true, ({
                    "error thrown",
                    err,
                })
            end)()
        end
        do
            print("finally")
        end
        if err then
            return unpack(____TS_returnValue)
        end
    end
end
```

### CODE REVIEW

File: src/LuaTransformer.ts [hunk 1]
```diff
@@ -2571,39 +2597,101 @@ export class LuaTransformer {
         }
     }
 
+    protected transformScopeBlock(block: ts.Block, scopeType: ScopeType): [tstl.Block, Scope] {
```
Comment (lolleko) [inline src/LuaTransformer.ts]: since this functions is only used for try/catch it might be better to name it accordingly, transformScopeBlock sounds a bit generic. Unless there are plans to use this function in more places in the future.

File: test/unit/error.spec.ts [hunk 2]
```diff
@@ -62,3 +62,194 @@ test("re-throw (no catch var)", () => {
...
+                return evaluate(e);
+            } finally {
+                return "finally";
+            }
+        }
+        return foobar() + " " + x;
+    `;
+    expect(util.transpileAndExecute(code)).toBe("finally evaluated");
+});
+
```
Comment (lolleko) [inline test/unit/error.spec.ts]: tuple return from finally?

File: src/LuaTransformer.ts (hunk 1 above)
Comment (tomblind) [reply src/LuaTransformer.ts]: It could be used for other purposes at well. It's really just an alternate form of transformBlock which returns the scope as well. I could just modify that function and use it everywhere.

File: src/LuaTransformer.ts [hunk 3]
```diff
@@ -2111,23 +2114,33 @@ export class LuaTransformer {
     }
 
     public transformReturnStatement(statement: ts.ReturnStatement): StatementVisitResult {
+        // Bubble up explicit return flag and check if we're inside a try/catch block
+        let insideTryCatch = false;
+        for (let i = this.scopeStack.length - 1; i >= 0; --i) {
```
Comment (Perryvw) [inline src/LuaTransformer.ts]: Can insideTryCatch be set to false after being true again? Otherwise you could also add `!insideTryCatch` to the loop condition here.

File: src/LuaTransformer.ts [hunk 4]
```diff
@@ -2571,39 +2597,101 @@ export class LuaTransformer {
...
         }
 
-        if (statement.finallyBlock) {
-            result.push(tstl.createDoStatement(this.transformBlock(statement.finallyBlock).statements));
+        if (statement.finallyBlock && statement.finallyBlock.statements.length > 0) {
+            result.push(...this.statementVisitResultToArray(this.transformBlockAsDoStatement(statement.finallyBlock)));
+        }
+
+        if (returnCondition && returnedIdentifier) {
+            // if [____TS_try and] ____TS_returned then return ____TS_returnValue end
```
Comment (Perryvw) [inline src/LuaTransformer.ts]: What's up with [____TS_try and], looks a little confusing to me. I the brackets have a specific meaning you can maybe explain it better, or just remove the brackets if not.

File: src/LuaTransformer.ts [hunk 5]
```diff
@@ -2571,39 +2597,101 @@ export class LuaTransformer {
...
-            result.push(tstl.createIfStatement(notTryResult, this.transformBlock(statement.catchClause.block)));
+            result.push(tstl.createIfStatement(notTryCondition, catchBlock));
+        } else if (tryScope.functionReturned) {
+            // try with return, but no catch
+            returnedIdentifier = tstl.createIdentifier("____TS_returned");
+            const returnedVariables = [tryResultIdentfier, returnedIdentifier, returnValueIdentifier];
+            result.push(tstl.createVariableDeclarationStatement(returnedVariables, tryCall));
+
+            // change return condition to '____TS_try and ____TS_returned'
+            returnCondition = tstl.createBinaryExpression(
```
Comment (Perryvw) [inline src/LuaTransformer.ts]: Maybe I'm looking at the wrong spot or misunderstanding, but how does this work when the try returns nil and that is loaded into ____TS_try?

File: test/unit/error.spec.ts [hunk 6]
```diff
@@ -62,3 +62,239 @@ test("re-throw (no catch var)", () => {
     const result = util.transpileAndExecute(source);
     expect(result).toBe("z");
 });
+
+test("return from try", () => {
+    const code = `
+        function foobar() {
+            try {
+                return "foobar";
```
Comment (Perryvw) [inline test/unit/error.spec.ts]: Can we get this test duplicated with a void return?

File: src/LuaTransformer.ts (hunk 4 above)
Comment (tomblind) [reply src/LuaTransformer.ts]: the brackets mean optionally: the `___TS_try and` is only required when there is no `catch`

File: src/LuaTransformer.ts (hunk 3 above)
Comment (tomblind) [reply src/LuaTransformer.ts]: If the loop exits on the first `try`/`catch` it hits, the `functionReturned` flag won't bubble up to nested try/catch statements.

File: src/LuaTransformer.ts (hunk 5 above)
Comment (tomblind) [reply src/LuaTransformer.ts]: The `nil` return value would be loaded in `____TS_returned` in that case.

File: test/unit/error.spec.ts (hunk 6 above)
Comment (tomblind) [reply test/unit/error.spec.ts]: That's what's being tested below in `return nil from try`, or am I misunderstanding what you're asking here?

Comment (Perryvw) [reply test/unit/error.spec.ts]: ah yes looked over that one.

File: src/LuaTransformer.ts (hunk 5 above)
Comment (Perryvw) [reply src/LuaTransformer.ts]: But `true and nil` would mean the condition is false?

Comment (tomblind) [reply src/LuaTransformer.ts]: Sorry, what I said before was incorrect.
- `____TS_try` will contain the success of the `pcall`
- `____TS_returned` will contain a boolean stating whether the clause returned or not
- `____TS_returnValue` would contain the `nil` that was actually returned.
