### PR TITLE
fix sourceMapTraceback

### LINKED ISSUE #1086: Sourcemap traceback doesn't work (`_G` is returned from debug.traceback)
SourceMap traceback currently causes `_G` to be returned from debug.traceback.

It seems that this is because `globalThis.__TS__originalTraceback` still thinks it has a `self` parameter, and so is translated to `globalThis:__TS__originalTraceback()`.

### PR DESCRIPTION
**Pull request by GlassBricks**
Fixes #1086

### CODE REVIEW

File: src/lualib/SourceMapTraceBack.ts [hunk 1]
```diff
@@ -9,9 +10,13 @@ function __TS__SourceMapTraceBack(this: void, fileName: string, sourceMap: { [li
         debug.traceback = ((thread, message, level) => {
             let trace: string;
             if (thread === undefined && message === undefined && level === undefined) {
-                trace = globalThis.__TS__originalTraceback();
+                trace = (globalThis.__TS__originalTraceback as (this: void, ...args: any) => string)();
```
Comment (Perryvw) [inline src/lualib/SourceMapTraceBack.ts:13]: These duplicate casts seem pretty ugly (actually it's ugly these function are any in the first place), would it work to just add
```ts
declare function __TS__originalTraceback(this: void, thread?: LuaThread, message?: string, level?: number);
```
At the top of the file?

Comment (GlassBricks) [reply src/lualib/SourceMapTraceBack.ts]: Yes, that does work...

For some reason, before, I was trying to do `declare let __Ts__originalTraceback : (//)=>any` and that didn't work, so I did the cast instead.
