### PR TITLE
fixed declarations that reference their own identifiers

### LINKED ISSUE #894: Referencing return value in callback passed as argument
[playground](https://typescripttolua.github.io/play#code/PQKhAIAEDsHsGUCmAbAZgSWgMQJbMeCMAFAAmiAxsgIYBOBqArtBQC46zTgAOtO0rABQA6UXQDmAZwBc4ZgGs4Ad2gBtALoBKWQDdYOUgG5ixfK3CTGAI0kU+VxLVmDN4ALwA+cHoPHi-VkdUagoCAAlqaFJ8cABvVFhYKzpZSVY+aHEAXxNEAA9uWFpzJhZ2TgtrW3tEQQorZ1dPb31SbXAIqJjY4nA+yps7HAdad3B6437welZGWi54xOSncAAiBKS6VazjHOIKTjTwAAsxy0GawV7+l3cvHqmp3gDBY+EN5c1J-pyvk3PqsNHABCFyGcDAYCSY6wRjIUg8DLmdZLLbEIA)

This is a similar situation to recursive functions. The correct lua should declare the variable separately from assigning it in these circumstances.
```lua
local h
h = ____exports.subscribe(
    function()
        print(h.foobar)
    end
)
```

### PR DESCRIPTION
**Pull request by tomblind**
fixes #894

### CODE REVIEW

File: src/transformation/utils/lua-ast.ts [hunk 1]
```diff
@@ -129,6 +129,19 @@ export function createHoistableVariableDeclarationStatement(
...
 
+function hasMultipleReferences(scope: Scope, identifiers: lua.Identifier | lua.Identifier[]) {
+    const scopeSymbols = scope.referencedSymbols;
+    if (!scopeSymbols) {
+        return false;
+    }
+
+    const referenceLists = isArray(identifiers)
+        ? identifiers.map(i => i.symbolId && scopeSymbols.get(i.symbolId))
+        : [identifiers.symbolId && scopeSymbols.get(identifiers.symbolId)];
```
Comment (ark120202) [inline src/transformation/utils/lua-ast.ts:140]:
```suggestion
    const referenceLists = castArray(identifiers).map(i => i.symbolId && scopeSymbols.get(i.symbolId));
```

File: test/unit/identifiers.spec.ts [hunk 2]
```diff
@@ -788,3 +788,39 @@ test("lua built-in as in constructor assignment", () => {
         export const result = new A("42").error;
     `.expectToMatchJsResult();
 });
+
+test("local variable declaration referencing self indirectly", () => {
```
Comment (ark120202) [inline test/unit/identifiers.spec.ts:792]: It doesn't seem to fit the `identifiers.spec.ts` test file, which generally tests identifier printing itself, not how it's used. I think it would make sense to test it along with self-calling function, or general assignment tests

File: src/transformation/utils/lua-ast.ts [hunk 3]
```diff
@@ -129,6 +128,17 @@ export function createHoistableVariableDeclarationStatement(
...
 
+function hasMultipleReferences(scope: Scope, identifiers: lua.Identifier | lua.Identifier[]) {
+    const scopeSymbols = scope.referencedSymbols;
+    if (!scopeSymbols) {
+        return false;
+    }
+
+    const referenceLists = castArray(identifiers).map(i => i.symbolId && scopeSymbols.get(i.symbolId));
+
+    return referenceLists.some(symbolRefs => symbolRefs && symbolRefs.length > 1);
```
Comment (Perryvw) [inline src/transformation/utils/lua-ast.ts:139]: Maybe
```suggestion
    return referenceLists.some(symbolRefs => symbolRefs?.length > 1);
```

Comment (tomblind) [reply src/transformation/utils/lua-ast.ts:139]: This change won't work as `symbolRefs?.length` resolves to `number | undefined` which can't be compared to a number like that. I could change it to something like `(symbolRefs?.length || 0) > 1`, but I feel like it looses clarity that way.
