### PR TITLE
Fix optimized vararg spread with casts

### LINKED ISSUE #1143: no table.unpack optimization when using cast to any[]
There probably shouldn't be a table.unpack when you cast parameters to any[] (or another array type). For instance:

https://typescripttolua.github.io/play/#code/FDBmFcDsGMBcEsD2kAEoCGMCeBhdAbfAHgDEUBTAD1nMgBMBnFACgDp30AnAcwYC4UmLAEoAvAD4h45hBgCSAGhTtWXXgIAKXdAFtyNTg1LjhAgEr7wnSABUsAB3LGA3sBTuUnS9bRRobdmY1JnQQyCwAbQBdYWFgAF8gA

Current workaround: make the function definition an overload and the implementation take `any[]` type as parameters

### PR DESCRIPTION
**Pull request by GlassBricks**
Fixes #1143.

Also fixes for other outer expressions.

### CODE REVIEW

File: src/transformation/visitors/errors.ts [hunk 1]
```diff
@@ -44,31 +44,38 @@ export const transformTryStatement: FunctionVisitor<ts.TryStatement> = (statemen
         const catchParameter = statement.catchClause.variableDeclaration
             ? transformIdentifier(context, statement.catchClause.variableDeclaration.name as ts.Identifier)
             : undefined;
-        const catchParameters = () => (catchParameter ? [lua.cloneIdentifier(catchParameter)] : []);
```
Comment (Perryvw) [inline src/transformation/visitors/errors.ts:47]: What happened here, this seems like the change from the other branch? Guess you need to merge master into this branch.

Comment (GlassBricks) [reply src/transformation/visitors/errors.ts]: Yeah, somehow those changes made it here.
I just force pushed a new commit without those changes
