### PR TITLE
Identifier name fixes

### LINKED ISSUE #594: More Identifier Issues
- shorthand assignment of variable declared with lua keyword name should produce error
```ts
declare var local: any;
const foo = { local };
```
- use of lua keywords as variables that are undeclared should produce the correct error
```ts
const foo = local;
```
- use of ambient indentifiers with invalid characters should produce error
```ts
declare var $foo: any;
$foo = 1;
```

Feel free to add to this list.

### PR DESCRIPTION
**Pull request by tomblind**
fixes #594

### CODE REVIEW

File: src/LuaTransformer.ts [hunk 1]
```diff
@@ -5277,23 +5277,28 @@ export class LuaTransformer {
...
 
-    protected hasUnsafeSymbolName(symbol: ts.Symbol): boolean {
-        if (luaKeywords.has(symbol.name) || luaBuiltins.has(symbol.name)) {
-            // lua keywords are only unsafe when non-ambient and not exported
-            const isNonAmbient = symbol.declarations.find(d => !tsHelper.isAmbient(d)) !== undefined;
-            return isNonAmbient && !this.isSymbolExported(symbol);
+    protected hasUnsafeSymbolName(symbol: ts.Symbol, tsOriginal?: ts.Identifier): boolean {
+        const isLuaKeyword = luaKeywords.has(symbol.name);
+        const isInvalidIdentifier = !tsHelper.isValidLuaIdentifier(symbol.name);
+        const isAmbient = symbol.declarations.find(d => !tsHelper.isAmbient(d)) === undefined;
```
Comment (ark120202) [inline src/LuaTransformer.ts]: Could be a bit cleaner with `some`:
```suggestion
        const isAmbient = symbol.declarations.some(d => tsHelper.isAmbient(d));
```

File: src/LuaTransformer.ts [hunk 2]
```diff
@@ -593,6 +592,7 @@ export class LuaTransformer {
                 statement,
                 className,
                 localClassName,
+                classNameText,
```
[the remark this answers is not in the document]
Comment (tomblind) [reply src/LuaTransformer.ts]: Yes, they are actually 2 different things. `localClassName` is the local variable used when setting up an exported class, and it will have a 'safe' name. `classNameText` is the display-name of the class and won't be manipulated at all.

**Comment by ark120202** [comment]
```ts
@decorator
export class $ {}
```

```lua
local ____exports = {}
____exports["$"] = {}
local _____24 = ____exports["$"]
_____24.name = "$"
_____24.__index = _____24
_____24.prototype = {}
_____24.prototype.__index = _____24.prototype
_____24.prototype.constructor = _____24
function _____24.new(...)
    local self = setmetatable({}, _____24.prototype)
    self:____constructor(...)
    return self
end
function _____24.prototype.____constructor(self)
end
$ = __TS__Decorate({decorator}, $)
return ____exports
```

On master it is `_____24 = __TS__Decorate({decorator}, _____24)`

File: src/LuaTransformer.ts [hunk 3]
```diff
@@ -3442,13 +3443,7 @@ export class LuaTransformer {
...
                 let identifier: tstl.Expression | undefined;
                 const valueSymbol = this.checker.getShorthandAssignmentValueSymbol(element);
-                if (valueSymbol !== undefined
-                    // Ignore declarations for things like NaN
-                    && !tsHelper.isStandardLibraryDeclaration(valueSymbol.valueDeclaration, this.program)) {
-                    identifier = this.createIdentifierFromSymbol(valueSymbol, element.name);
-                } else {
-                    identifier = this.transformIdentifierExpression(element.name);
-                }
+                identifier = this.createShorthandIdentifier(valueSymbol, element.name);
```
Comment (ark120202) [inline src/LuaTransformer.ts]:
```diff
-let identifier: tstl.Expression | undefined;
-identifier = this.createShorthandIdentifier(valueSymbol, element.name);
+let identifier = this.createShorthandIdentifier(valueSymbol, element.name);
```

File: test/unit/classDecorator.spec.ts [hunk 4]
```diff
@@ -188,3 +188,16 @@ test("Throws error if decorator function has void context", () => {
...
+    const code = `
+        function decorator<T extends any>(c: T): T {
+            c.bar = "foobar";
+            return c;
+        }
+
+        @decorator
+        export class Foo {}`;
+
+    expect(util.transpileExecuteAndReturnExport(code, "Foo.bar"));
```
Comment (Perryvw) [inline test/unit/classDecorator.spec.ts]: Is there supposed to be an assertion here?
