### PR TITLE
Fix namespace and module resulting in invalid Lua when modified with TS transformer plugin

### LINKED ISSUE #1013: Exported namespace transformed by a TS transformer plugin generates invalid Lua
TS:
```ts
export namespace ns {
    export function returnsBool() {
        return false;
    }
}
```
Produces the following incorrect Lua, **ONLY** if changing an AST node with a TS transformer plugin. For example rewriting false to true:
```lua
local ____exports = {}
do
    function ns.returnsBool(self)
        return true
    end
end
return ____exports
```
Resulting in failure:
`attempt to index a nil value (global 'ns')`

Probably caused by a similar issue as solved in #1010

### PR DESCRIPTION
**Pull request by Perryvw**
Fixes #1013

### CODE REVIEW

File: test/transpile/plugins/transformer-plugin.js [hunk 1]
```diff
@@ -0,0 +1,18 @@
+/**
```
Comment (lolleko) [inline test/transpile/plugins/transformer-plugin.js:1]: Where is the `.ts` source for this file?

Comment (Perryvw) [reply test/transpile/plugins/transformer-plugin.js:1]: I did not add TS source as it would mean adding another step to our test or test run to compile it. We could do that at some point if we have more code like this, but for now I don't know if it would add much.

**Review by lolleko — APPROVED** [review]
