### PR TITLE
Fix `array.join` accepting only string and number elements

### LINKED ISSUE #841: `Array.prototype.join` doesn't work on tables
[Playground](https://typescripttolua.github.io/play#code/A4JwlgdgLgFA2gbwL4F0B0ArA9pGBKPIA)

**Input:**
```ts
print([{}].join())
```

**Current Result:**
```lua
print(
    table.concat({{}}, ",") -- invalid value (table) at index 1 in table for 'concat'
)
```

**Expected Result:**
```lua
function __TS__ArrayJoin(self, separator)
	if separator == nil then separator = ", " end

	local result = ""
	for index, value in ipairs(self) do
		if index > 1 then
			result = result + separator
		end
		result = result + tostring(value)
	end
	return result
end

print(
    __TS__ArrayJoin({{}}, ",") -- "table: 0x25"
)
```

### PR DESCRIPTION
**Pull request by ark120202**
Fixes #841

### CODE REVIEW

File: src/lualib/Iterator.ts [hunk 1]
```diff
@@ -27,6 +27,6 @@ function __TS__Iterator<T>(
         const iterator = iterable[Symbol.iterator]();
         return [__TS__IteratorIteratorStep, iterator];
     } else {
-        return ipairs(iterable as readonly T[]);
+        return ipairs(iterable as readonly T[]) as any;
```
Comment (Perryvw) [inline src/lualib/Iterator.ts:30]: What is the reasoning behind this `as any?`

Comment (ark120202) [reply src/lualib/Iterator.ts:30]: `ipairs` returns a `LuaTupleIterator` which is incompatible with `__TS__Iterator` signature. Generally this should be resolved with 880
