### PR TITLE
Fixed out of spec behavior of array.reduce

### LINKED ISSUE #727: Array.reduce should accept undefined as an initial value
```ts
console.log([].reduce(() => {}, undefined)); // should be undefined
```

[TypescriptToLua Playground](https://typescripttolua.github.io/play.html#src=console.log(%5B%5D.reduce(()%20%3D%3E%20%7B%7D%2C%20undefined))%3B)

[TS Playground](https://www.typescriptlang.org/play/#code/MYewdgziA2CmB00QHMAUBtAuvATrAJgK7CyqoCUABALwB8lA3gL4A0lhY+sAZgJZgFy5ANxA)

This is the more correct code roblox-ts uses:

```lua
function TS.array_reduce(list, callback, ...)
	local first = 1
	local last = #list
	local accumulator
	-- support `nil` initialValues
	if select("#", ...) == 0 then
		if last == 0 then
			error("Reduce of empty array with no initial value at Array.reduce", 2)
		end
		accumulator = list[first]
		first = first + 1
	else
		accumulator = ...
	end
	for i = first, last do
		accumulator = callback(accumulator, list[i], i - 1, list)
	end
	return accumulator
end

function TS.array_reduceRight(list, callback, ...)
	local first = #list
	local last = 1
	local accumulator
	-- support `nil` initialValues
	if select("#", ...) == 0 then
		if first == 0 then
			error("Reduce of empty array with no initial value at Array.reduceRight", 2)
		end
		accumulator = list[first]
		first = first - 1
	else
		accumulator = ...
	end
	for i = first, last, -1 do
		accumulator = callback(accumulator, list[i], i - 1, list)
	end
	return accumulator
end
```

### PR DESCRIPTION
**Pull request by Perryvw**
Fixes #727

### CODE REVIEW

File: src/lualib/ArrayReduce.ts [hunk 1]
```diff
@@ -1,20 +1,23 @@
+/** @vararg */
+interface VarArg<T> extends Array<T> {}
```
Comment (ark120202) [inline src/lualib/ArrayReduce.ts]:
```suggestion
interface Vararg<T> extends Array<T> {}
```

File: src/lualib/ArrayReduce.ts [hunk 2]
```diff
@@ -1,20 +1,23 @@
...
+    if (len === 0 && select("#", ...initial) === 0) {
         // tslint:disable-next-line: no-string-throw
         throw "Reduce of empty array with no initial value";
     }
 
     let k = 0;
-    let accumulator = initial;
-    if (initial === undefined) {
+    let accumulator = select(1, ...initial);
+    if (accumulator === undefined) {
```
Comment (ark120202) [inline src/lualib/ArrayReduce.ts]: It doesn't look like that would fix that issue. The test case doesn't cover it, but:

```ts
['a', 'b'].reduce((a, b) => console.log(a, b));
// "a" "b"
['a', 'b'].reduce((a, b) => console.log(a, b), undefined);
// undefined "a"
// undefined "b"
```

File: src/lualib/ArrayReduce.ts [hunk 3]
```diff
@@ -1,20 +1,23 @@
...
     this: void,
     arr: T[],
     callbackFn: (accumulator: T, currentValue: T, index: number, array: T[]) => T,
-    initial?: T
+    ...initial: VarArg<T>
 ): T {
     const len = arr.length;
 
-    if (len === 0 && initial === undefined) {
+    if (len === 0 && select("#", ...initial) === 0) {
```
Comment (ark120202) [inline src/lualib/ArrayReduce.ts]: That's out of scope of this PR, but we probably want to transform `vararg.length` to `select("#", ...)` in general

File: src/lualib/ArrayReduce.ts [hunk 4]
```diff
@@ -1,27 +1,35 @@
+/** @vararg */
+interface Vararg<T> extends Array<T> {}
```
Comment (ark120202) [inline src/lualib/ArrayReduce.ts]: I think we should move it to something like declarations/tstl.d.ts

File: src/lualib/ArrayReduce.ts [hunk 5]
```diff
@@ -1,27 +1,35 @@
...
     arr: T[],
     callbackFn: (accumulator: T, currentValue: T, index: number, array: T[]) => T,
-    initial?: T
+    ...initial: Vararg<T>
 ): T {
     const len = arr.length;
 
-    if (len === 0 && initial === undefined) {
+    const initialValuePresent = select("#", ...initial) !== 0;
+    if (len === 0 && !initialValuePresent) {
```
Comment (ark120202) [inline src/lualib/ArrayReduce.ts]: Thoughts on moving that check to a condition below and removing `initialValuePresent` variable?

File: test/unit/builtins/array.spec.ts [hunk 6]
```diff
@@ -486,6 +486,22 @@ test.each<[[(total: number, currentItem: number, index: number, array: number[])
...
+    util.testExpression`[].reduce(() => {}, undefined)`.expectToMatchJsResult();
+});
+
+test("array.reduce empty no initial", () => {
+    util.testExpression`[].reduce(() => {})`.expectToMatchJsResult(true);
+});
+
+test("array.reduce undefined returning callback", () => {
+    util.testFunction`
+        const calls: {a: void, b: string}[] = [];
```
Comment (ark120202) [inline test/unit/builtins/array.spec.ts]:
```suggestion
        const calls: Array<{ a: void, b: string }> = [];
```
