### PR TITLE
Fixed referencing named function expressions

### LINKED ISSUE #669: Function expressions can have names. This is not accounted for
```ts
const y = function x() {
    x();
}
```

```lua
local y
y = function(self)
    x(_G)
end
```

[Playground Link](https://typescripttolua.github.io/play.html#src=const%20y%20%3D%20function%20x()%20%7B%0A%20%20%20%20x()%3B%0A%7D%0A)

### PR DESCRIPTION
**Pull request by tomblind**
fixes #669

```ts
const y = function x() {
    x();
}
```
=>
```lua
local y
y = (function()
    local function x(self)
        x(_G)
    end
    return x
end)()
```

### CODE REVIEW

File: src/LuaTransformer.ts [hunk 1]
```diff
@@ -3664,16 +3664,32 @@ export class LuaTransformer {
...
             spreadIdentifier,
             flags,
             node
         );
+
+        if (ts.isFunctionExpression(node) && node.name && scope.referencedSymbols) {
+            const symbol = this.checker.getSymbolAtLocation(node.name);
+            if (symbol) {
+                const symbolId = this.symbolIds.get(symbol);
+                if (symbolId && scope.referencedSymbols.has(symbolId)) {
```
Comment (ark120202) [inline src/LuaTransformer.ts]:
```suggestion
                if (symbolId !== undefined && scope.referencedSymbols.has(symbolId)) {
```

It can't happen in practice, since `genSymbolIdCounter` always starts from `1`, but I think it's better to keep things safe when checking numbers and strings.

We probably should enable `strict-boolean-expressions` after we'll migrate to eslint.

Comment (tomblind) [reply src/LuaTransformer.ts]: Good catch. I'm definitely in favor of enabling `strict-boolean-expressions`.

File: src/LuaTransformer.ts [hunk 2]
```diff
@@ -3664,16 +3664,32 @@ export class LuaTransformer {
...
+        const functionExpression = tstl.createFunctionExpression(
             tstl.createBlock(transformedBody),
             paramNames,
             dotsLiteral,
             spreadIdentifier,
             flags,
             node
         );
+
+        if (ts.isFunctionExpression(node) && node.name && scope.referencedSymbols) {
```
Comment (Perryvw) [inline src/LuaTransformer.ts]: Would probably not be a bad idea if y ou added a comment above this block saying this handles named function assignments.

File: src/LuaTransformer.ts [hunk 3]
```diff
@@ -3664,16 +3664,32 @@ export class LuaTransformer {
...
+            const symbol = this.checker.getSymbolAtLocation(node.name);
+            if (symbol) {
+                const symbolId = this.symbolIds.get(symbol);
+                if (symbolId !== undefined && scope.referencedSymbols.has(symbolId)) {
```
Comment (Perryvw) [inline src/LuaTransformer.ts]: It is not clear to me what the purpose of this check is.
